[workspace]
members = [
    "mullvad-daemon",
    "mullvad-cli",
    "mullvad-problem-report",
    "mullvad-ipc-client",
    "mullvad-jni",
    "mullvad-paths",
    "mullvad-types",
    "mullvad-rpc",
    "mullvad-tests",
    "talpid-openvpn-plugin",
    "talpid-core",
    "talpid-ipc",
]
exclude = ["dist-assets/binaries/shadowsocks-rust"]


[profile.release]
lto = "off"
